name: flutter_qr_reader_plus
description: QR code (scan QRCode and picture) recognition （AndroidView/UiKitView）
version: 1.0.6
homepage: https://github.com/wanghongen/flutter_qr_reader_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  image_pickers: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: me.hetian.flutter_qr_reader
        pluginClass: FlutterQrReaderPlugin
      ios:
        pluginClass: FlutterQrReaderPlugin

  assets:
    - assets/tool_img.png
    - assets/tool_qrcode.png
    - assets/tool_flashlight_close.png
    - assets/tool_flashlight_open.png
